### ISSUE TITLE
Long audio initialization time in Pulseaudio

### ISSUE THREAD

**Issue by haarp** [michaellass/ladspa-notch-harmonics#2] opened 2021-10-01 10:08 UTC
Hello again,

I've been using this for a few days now and have noticed on problem so far. When the module is selected as the playback sink, it causes a delay when an audio stream starts. It takes roughly 2-3 seconds until sound can be heard. This is obvious when playing movies, which will freeze before starting to play. Once the stream is playing, the delay normalizes to acceptable values.

Reproduction:

- Start with fresh Pulseaudio config
- `pacmd load-module module-ladspa-sink sink_name=test master=alsa_output.pci-0000_00_1f.3.analog-stereo plugin=$path/notch_harmonics_5761 label=notch_harmonics control=116.5,1`
- Select sink as playback device
- Make sure no other audio is playing
- aplay /dev/urandom # warning: loud

There will be a few seconds until audio starts playing.

- Selecting the raw playback device gets rid of the delay. Only selecting the ladspa-sink as playback device triggers this bug
- If another stream is already playing audio, no delay is observed starting another stream.
- `module-suspend-on-idle` is innocent, as unloading that module will not solve this problem
- Restarting Pulseaudio made no difference
- Before/during the delay, `pacmd list-sinks` shows the ladspa-sink's `current latency` going over 1000ms, but it will settle down to <150ms once playback is in progress
- Other ladspa plugins appear to have the same issue

This is likely a Pulseaudio/module-ladspa-sink bug, but maybe you have some insights regardless? Thanks!

**Comment by michaellass** [comment] 2021-10-01 18:49
I can easily reproduce the issue with PulseAudio 15.0 using your supplied commands. I'm not very familiar with the internals of PulseAudio. However, here is what I could find out:

If you run PulseAudio with verbose output, you get an output like the following as soon as the audio stream starts:
```
I: [pulseaudio] protocol-native.c: Requested tlength=500.00 ms, minreq=125.00 ms
I: [pulseaudio] protocol-native.c: Final latency 625.00 ms = 250.00 ms + 2*125.00 ms + 125.00 ms
```
To reproduce, you can start PulseAudio in foreground with verbose output as follows:
```
systemctl --user stop pulseaudio.socket
systemctl --user stop pulseaudio.service
pulseaudio -v
[set up the LADSPA sink as described in your post]
```
The latency differs depending on the audio source. For example, if I perform GNOME's speaker test instead of using `aplay`, I get the following:
```
I: [pulseaudio] protocol-native.c: Requested tlength=2000.00 ms, minreq=20.00 ms
I: [pulseaudio] protocol-native.c: Final latency 3960.00 ms = 1960.00 ms + 2*20.00 ms + 1960.00 ms
```
The sample rate of the audio has a small influence but does not seems to be the root cause. All of the following commands suffer from severe latency:
```
aplay /dev/random
aplay -f cd /dev/random
aplay -f dat /dev/random
```
The verbose output comes from https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/blob/master/src/pulsecore/protocol-native.c#L1101. To me this looks like the latency depends on the size of a buffer introduced somewhere in the audio pipe.

`module-ladspa-sink` itself does not seem to introduce an explicit latency. At least I could not find anything like that in: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/blob/master/src/modules/module-ladspa-sink.c.

Maybe you could report this to the PulseAudio folks at https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues? I suggest leaving this issue open until we know what's going on.

**Comment by haarp** [comment] 2021-10-07 09:52
Thanks for having a look. So it looks like the ladspa sink prefers filling its buffers before starting to drain? That seems dumb. Ehh, I've had mixed experiences with filing Pulseaudio bugs. Most bugs will languish unread for the rest of eternity :/

Anyway, this issue made me check out [Pipewire](https://en.wikipedia.org/wiki/PipeWire). It's kind of the love child of Pulseaudio and JACK, with focus on low CPU usage and latency. It still has some bugs on its own, but a healthy and active dev team. LADSPA plugins can be loaded into filter chains, solving my use case without any ladded latency :)

Feel free to close this at your discretion.

**Comment by michaellass** [comment] 2021-10-09 20:59
Good to hear that you found a workaround. I'm sure Pipewire will take over in the next couple of years. For now I personally stick to PulseAudio because it works well for me. As this is clearly a PulseAudio issue, I'll close this issue for now.

If anyone else suffers from this issue and reports it to the PulseAudio folks, please let us know.

**Closed as completed by michaellass** 2021-10-09 20:59 UTC
